baseURL = 'https://shweata-hegde-blog.netlify.app/'
languageCode = 'en-us'
title = "Shweata's Blog"
theme = "PaperMod"
pagination.pagerSize = 5

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = [ "posts", "papermod" ]

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

  [languages.en.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[languages.en.menu.main]]
name = "Archive"
url = "archives"
weight = 30

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[[languages.en.menu.main]]
name = "Assignments"
url = "assignments/"
weight = 7

[[languages.en.menu.main]]
name = "Personal Website"
url = "https://shweata-hegde.netlify.app/"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[Site.params]
env = "production"
description = "Shweata's blog page"
author = "Shweata"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
images = [ "images/papermod-cover.png" ]

  [params.profileMode]
  enabled = false
  title = "PaperMod"
  imageUrl = "#"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Shweata's Blog"
  Content = """
👋 Welcome to my blog page! I'm Shweata. I like to write and talk about science; build websites and open source tools.

I always wanted a corner on the internet where I document the way I perceive the world, keep track of learnings (science-y stuff, and maybe life lessons), and ramble. I have lost track of the number of failed attempts to set up a blog site. Let's see if this website sticks around.
"""

  [[params.socialIcons]]
  name = "X"
  title = "Follow me on Twitter"
  url = "https://x.com/shweataHegde"

  [params.editPost]
  URL = "#"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true